# Generated by Django 2.2 on 2020-12-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmessage',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='commentmessage',
            old_name='to_user_id',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='commentmessage',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='imessage',
            old_name='to_user_id',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='imessage',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reportmessage',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='reportmessage',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reportmessage',
            old_name='to_user_id',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='starmessage',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='starmessage',
            old_name='to_user_id',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='starmessage',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='reportmessage',
            name='rid',
        ),
    ]
