# Generated by Django 2.2 on 2020-12-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20201215_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmessage',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterModelOptions(
            name='imessage',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterModelOptions(
            name='reportmessage',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterModelOptions(
            name='starmessage',
            options={'ordering': ('-time',)},
        ),
        migrations.AddField(
            model_name='reportmessage',
            name='author_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
