# Generated by Django 2.2 on 2020-12-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_reportid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
