# Generated by Django 2.2 on 2020-12-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20201215_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='author_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='author_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
