# Generated by Django 2.2 on 2020-12-04 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201202_1712'),
        ('blog', '0005_like_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_collect',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_like',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('collectBlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
    ]
