# Generated by Django 2.2 on 2020-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201204_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='htmlcontent',
            field=models.TextField(blank=True),
        ),
    ]
