# Generated by Django 2.2 on 2020-12-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='realname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
