# Generated by Django 2.2 on 2020-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_realname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
