# Generated by Django 2.2 on 2020-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20201126_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
